trigger:
- master

pool: default

steps:
- task: CMakeNode16@1
  inputs:
    workingDirectory: 'src'
    cmakeArgs: -DCMAKE_SHELL=false -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_WIN_VARIABLE=test -DTEST_VARIABLE=test
    runInsideShell: false
- task: CMakeNode16@1
  inputs:
    workingDirectory: 'src'
    cmakeArgs: -DCMAKE_SHELL=true -DTEST_ONE=one;two -DTEST_TWO=/one/two/three -DTEST_VARIABLE=$USER -DTEST_WIN_VARIABLE=%OS%
    runInsideShell: true